### PR TITLE
dev_pier updates

### PR DESCRIPTION
**Pull request by peterbetos**
- updating the `ImageView` widgets to use `app:srcCompat `for better backward compatibility
- updated build.gradle to later tool and library versions

### CODE REVIEW

**Comment by peterbetos** [comment]
@Mauker1 Should I need to perform rebase for this? Or is it possible to merge this even with the warning above? Thanks.

**Comment by peterbetos** [comment]
@Mauker1 Just resolved the conflicts. 😄

**Comment by Mauker1** [comment]
Travis build failed @peterbetos - Could you take a look?

**Comment by peterbetos** [comment]
Will check before the day ends. Man this pure vector support doesn't go down all the way to SDK 14. Sad thing really. I'll close this in the meantime so that your code will be left untouched while Google is still resolving pure backward compatibility.

**Comment by Mauker1** [comment]
Ok, let's wait. Thanks!

**Pull request closed without merging**
